// Code generated by mockery. DO NOT EDIT.

package consulapimock

import (
	api "github.com/hashicorp/consul/api"

	mock "github.com/stretchr/testify/mock"
)

// ConsulKV is an autogenerated mock type for the ConsulKV type
type ConsulKV struct {
	mock.Mock
}

type ConsulKV_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsulKV) EXPECT() *ConsulKV_Expecter {
	return &ConsulKV_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key, q
func (_m *ConsulKV) Get(key string, q *api.QueryOptions) (*api.KVPair, *api.QueryMeta, error) {
	ret := _m.Called(key, q)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *api.KVPair
	var r1 *api.QueryMeta
	var r2 error
	if rf, ok := ret.Get(0).(func(string, *api.QueryOptions) (*api.KVPair, *api.QueryMeta, error)); ok {
		return rf(key, q)
	}
	if rf, ok := ret.Get(0).(func(string, *api.QueryOptions) *api.KVPair); ok {
		r0 = rf(key, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.KVPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *api.QueryOptions) *api.QueryMeta); ok {
		r1 = rf(key, q)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.QueryMeta)
		}
	}

	if rf, ok := ret.Get(2).(func(string, *api.QueryOptions) error); ok {
		r2 = rf(key, q)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConsulKV_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ConsulKV_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
//   - q *api.QueryOptions
func (_e *ConsulKV_Expecter) Get(key interface{}, q interface{}) *ConsulKV_Get_Call {
	return &ConsulKV_Get_Call{Call: _e.mock.On("Get", key, q)}
}

func (_c *ConsulKV_Get_Call) Run(run func(key string, q *api.QueryOptions)) *ConsulKV_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*api.QueryOptions))
	})
	return _c
}

func (_c *ConsulKV_Get_Call) Return(_a0 *api.KVPair, _a1 *api.QueryMeta, _a2 error) *ConsulKV_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ConsulKV_Get_Call) RunAndReturn(run func(string, *api.QueryOptions) (*api.KVPair, *api.QueryMeta, error)) *ConsulKV_Get_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsulKV creates a new instance of ConsulKV. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsulKV(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsulKV {
	mock := &ConsulKV{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
