// Code generated by mockery. DO NOT EDIT.

package consulapimock

import (
	consulapi "github.com/peczenyj/runtimevar-consul/consulvar/consulapi"
	mock "github.com/stretchr/testify/mock"
)

// ConsulClient is an autogenerated mock type for the ConsulClient type
type ConsulClient struct {
	mock.Mock
}

type ConsulClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ConsulClient) EXPECT() *ConsulClient_Expecter {
	return &ConsulClient_Expecter{mock: &_m.Mock}
}

// KV provides a mock function with no fields
func (_m *ConsulClient) KV() consulapi.ConsulKV {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for KV")
	}

	var r0 consulapi.ConsulKV
	if rf, ok := ret.Get(0).(func() consulapi.ConsulKV); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(consulapi.ConsulKV)
		}
	}

	return r0
}

// ConsulClient_KV_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KV'
type ConsulClient_KV_Call struct {
	*mock.Call
}

// KV is a helper method to define mock.On call
func (_e *ConsulClient_Expecter) KV() *ConsulClient_KV_Call {
	return &ConsulClient_KV_Call{Call: _e.mock.On("KV")}
}

func (_c *ConsulClient_KV_Call) Run(run func()) *ConsulClient_KV_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConsulClient_KV_Call) Return(_a0 consulapi.ConsulKV) *ConsulClient_KV_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ConsulClient_KV_Call) RunAndReturn(run func() consulapi.ConsulKV) *ConsulClient_KV_Call {
	_c.Call.Return(run)
	return _c
}

// NewConsulClient creates a new instance of ConsulClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConsulClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConsulClient {
	mock := &ConsulClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
